name: CI

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linter
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Coverage
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm run coverage

  nightly_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Nightly Build
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm run truffle:test
        env:
          SOLC_NIGHTLY: true
